dist: trusty

env:
  NODE_ENV=test

language: node_js

node_js:
  - "node"

cache:
  directories:
    - "node_modules"

notifications:
  email: false

addons:
  postgresql: "9.6"

services:
  - postgresql
  - redis-server

before_script:
  - psql -c 'create database bugfree_test;' -U postgres
