---
- hosts: [ prod ]
  become: true
  tasks:
    - name: sync favicons
      synchronize: src=../assets/favicons/ dest=/var/www/html/images rsync_opts="--chown=www-data:www-data" delete=yes

    - name: sync static
      synchronize: src=../static dest=/var/www/html rsync_opts="--chown=www-data:www-data" delete=yes

    - name: sync views
      synchronize: src=../views dest=/var/www/html rsync_opts="--chown=www-data:www-data" delete=yes

    - name: sync migrations
      synchronize: src=../migrations dest=/var/www/html rsync_opts="--chown=www-data:www-data" delete=yes

    - name: sync server
      synchronize: src=../server/ dest=/var/www/html/server rsync_opts="--chown=www-data:www-data" delete=yes

    - name: copy files
      copy: src=../{{item}} dest=/var/www/html/{{item | basename}} owner=www-data group=www-data
      with_items:
        - package.json
        - browserconfig.xml
        - manifest.json
        - ansible/ecosystem.config.js

    - name: install dependencies
      npm: path=/var/www/html

    - name: start the server
      command: 'pm2 restart ecosystem.config.js'
      args:
        chdir: /var/www/html
      become: false
      environment:
        DB_USER: "{{db_user}}"
        DB_PASSWORD: "{{db_password}}"
        SESSION_SECRET: "{{session_secret}}"

